Description: >
    Jose Berrocal / Able
    This is a demo and update

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    KeyName:
        Description: The EC2 Key Pair to allow SSH access to the instances
        Type: AWS::EC2::KeyPair::KeyName

    NodeImageId:
        Type: AWS::EC2::Image::Id
        Description: AMI id for the node instances.

    InstanceType:
        Description: EC2 instance type for the node instances
        Type: String
        Default: t3.small
        AllowedValues:
        - t2.small
        - t2.medium
        - t2.large
        - t2.xlarge
        - t2.2xlarge
        - t3.nano
        - t3.micro
        - t3.small
        - t3.medium
        ConstraintDescription: Must be a valid EC2 instance type

    InstaceName:
        Description: Name of the Jump Server
        Type: String

Resources:


  JumpServSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to a jumpserver
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref NodeImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: 
          - !GetAtt "JumpServSecGroup.GroupId"
      SubnetId:
        Fn::ImportValue: 
          Fn::Sub: "${EnvironmentName}-PUB1-SN"
      Tags:
      - Key: Name
        Value: !Ref InstaceName