name: repo-workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        make install
        wget -O venv/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 && chmod +x venv/bin/hadolint
    - name: Lint with pylint
      run: |
        . venv/bin/activate
        make lint
#    - name: Test with pytest
#      run: |
#        make test